//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GluttonyCombo.Resources.Localization.JobConfigs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BST_Config {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BST_Config() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GluttonyCombo.Resources.Localization.JobConfigs.BST_Config", typeof(BST_Config).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow knockback / draw-in {0}.
        /// </summary>
        internal static string AllowDisplacingRelease0 {
            get {
                return ResourceManager.GetString("AllowDisplacingRelease0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puk, diremite and treant knock enemies back; gigantoad and rotting goobbue dr....
        /// </summary>
        internal static string AllowDisplacingReleaseDesc {
            get {
                return ResourceManager.GetString("AllowDisplacingReleaseDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow cycling into no familiar.
        /// </summary>
        internal static string AllowPetlessCycling {
            get {
                return ResourceManager.GetString("AllowPetlessCycling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off (recommended): a familiar only retreats when another assigned Battlehorn ....
        /// </summary>
        internal static string AllowPetlessCyclingDesc {
            get {
                return ResourceManager.GetString("AllowPetlessCyclingDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow sleep {0} (lamb Lullaby).
        /// </summary>
        internal static string AllowSleepRelease0 {
            get {
                return ResourceManager.GetString("AllowSleepRelease0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lullaby puts enemies to sleep, which breaks on damage. Off (recommended): lam....
        /// </summary>
        internal static string AllowSleepReleaseDesc {
            get {
                return ResourceManager.GetString("AllowSleepReleaseDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use {0} while {1} is recasting.
        /// </summary>
        internal static string BorrowWhileReleaseRecasts0 {
            get {
                return ResourceManager.GetString("BorrowWhileReleaseRecasts0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levels 22-29: summoning does not reset the Tempered Release recast yet. On: a....
        /// </summary>
        internal static string BorrowWhileReleaseRecastsDesc {
            get {
                return ResourceManager.GetString("BorrowWhileReleaseRecastsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use wespe's Final Sting as its exit.
        /// </summary>
        internal static string FinalStingAsExit {
            get {
                return ResourceManager.GetString("FinalStingAsExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wespe's {0} skill (Final Sting) makes it retreat. On: it fires only as the we....
        /// </summary>
        internal static string FinalStingAsExitDesc {
            get {
                return ResourceManager.GetString("FinalStingAsExitDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum seconds a familiar fights before {0}.
        /// </summary>
        internal static string MinFamiliarStay0 {
            get {
                return ResourceManager.GetString("MinFamiliarStay0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh One with Nature between pulls.
        /// </summary>
        internal static string RefreshBetweenPulls {
            get {
                return ResourceManager.GetString("RefreshBetweenPulls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From level 18, out of combat with an enemy targeted: when the current familia....
        /// </summary>
        internal static string RefreshBetweenPullsDesc {
            get {
                return ResourceManager.GetString("RefreshBetweenPullsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (after Borrow, level 22+).
        /// </summary>
        internal static string SectionBeastMode0 {
            get {
                return ResourceManager.GetString("SectionBeastMode0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Familiar handling.
        /// </summary>
        internal static string SectionFamiliar {
            get {
                return ResourceManager.GetString("SectionFamiliar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string SectionOther {
            get {
                return ResourceManager.GetString("SectionOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summon a familiar when a hostile target is selected.
        /// </summary>
        internal static string SummonBeforeCombat {
            get {
                return ResourceManager.GetString("SummonBeforeCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of combat, summoning costs no lockout. Summons the first ready horn when ....
        /// </summary>
        internal static string SummonBeforeCombatDesc {
            get {
                return ResourceManager.GetString("SummonBeforeCombatDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In combat, on cooldown: less physical damage taken and higher critical hit ra....
        /// </summary>
        internal static string UseBeastskinDesc {
            get {
                return ResourceManager.GetString("UseBeastskinDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is a GCD spell: only when the target is out of melee range (up to 30 yalms....
        /// </summary>
        internal static string UseQuellingWaveRangedDesc {
            get {
                return ResourceManager.GetString("UseQuellingWaveRangedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use {0} and {1}.
        /// </summary>
        internal static string UseRally0And1 {
            get {
                return ResourceManager.GetString("UseRally0And1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rally at 3 Mastered Instinct right after the axe that granted the third. Rall....
        /// </summary>
        internal static string UseRallyDesc {
            get {
                return ResourceManager.GetString("UseRallyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When an enemy is targeting the character. Off by default: the barrier only pa....
        /// </summary>
        internal static string UseScaleskinDesc {
            get {
                return ResourceManager.GetString("UseScaleskinDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When an enemy is within 6 yalms..
        /// </summary>
        internal static string UseSeedsowerDesc {
            get {
                return ResourceManager.GetString("UseSeedsowerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As a gap closer when the target is 4-20 yalms away, and for damage in melee r....
        /// </summary>
        internal static string UseShieldChargeDesc {
            get {
                return ResourceManager.GetString("UseShieldChargeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only to interrupt an interruptible cast in melee range..
        /// </summary>
        internal static string UseSoulCrushDesc {
            get {
                return ResourceManager.GetString("UseSoulCrushDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When an enemy is targeting the character..
        /// </summary>
        internal static string UseVileskinDesc {
            get {
                return ResourceManager.GetString("UseVileskinDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crucible of the Unbroken.
        /// </summary>
        internal static string SectionCrucible {
            get {
                return ResourceManager.GetString("SectionCrucible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crucible rules.
        /// </summary>
        internal static string Crucible {
            get {
                return ResourceManager.GetString("Crucible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only on a Crucible board. Sends a familiar away with Parting Blow before it i....
        /// </summary>
        internal static string CrucibleDesc {
            get {
                return ResourceManager.GetString("CrucibleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send the familiar away with {0} at or below this HP %.
        /// </summary>
        internal static string CruciblePetSaveHp0 {
            get {
                return ResourceManager.GetString("CruciblePetSaveHp0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wespe's {0} (Final Sting) only at or below this target HP % (half with 2+ ene....
        /// </summary>
        internal static string CrucibleFinalStingHp0 {
            get {
                return ResourceManager.GetString("CrucibleFinalStingHp0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} / {1}.
        /// </summary>
        internal static string CrucibleAggro0And1 {
            get {
                return ResourceManager.GetString("CrucibleAggro0And1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string CrucibleAggroOff {
            get {
                return ResourceManager.GetString("CrucibleAggroOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log only.
        /// </summary>
        internal static string CrucibleAggroShadow {
            get {
                return ResourceManager.GetString("CrucibleAggroShadow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        internal static string CrucibleAggroOn {
            get {
                return ResourceManager.GetString("CrucibleAggroOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snarl on Directional Parry, on known single-target hits, or when the characte....
        /// </summary>
        internal static string CrucibleAggroDesc {
            get {
                return ResourceManager.GetString("CrucibleAggroDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow knockback / draw-in {0} in the Crucible.
        /// </summary>
        internal static string CrucibleAllowDisplacing0 {
            get {
                return ResourceManager.GetString("CrucibleAllowDisplacing0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo content: moving the enemy costs nothing there. Overrides the general set....
        /// </summary>
        internal static string CrucibleAllowDisplacingDesc {
            get {
                return ResourceManager.GetString("CrucibleAllowDisplacingDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warn when no beasts are assigned.
        /// </summary>
        internal static string CrucibleHornWarning {
            get {
                return ResourceManager.GetString("CrucibleHornWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horns deselect after every Crucible encounter. Out of combat, with the next b....
        /// </summary>
        internal static string CrucibleHornWarningDesc {
            get {
                return ResourceManager.GetString("CrucibleHornWarningDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crucible: no beasts are assigned to the Battlehorns..
        /// </summary>
        internal static string CrucibleHornWarningMessage {
            get {
                return ResourceManager.GetString("CrucibleHornWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not on a Crucible board..
        /// </summary>
        internal static string CrucibleStatusOutside {
            get {
                return ResourceManager.GetString("CrucibleStatusOutside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: no panel enemy in sight..
        /// </summary>
        internal static string CrucibleStatusBoard0 {
            get {
                return ResourceManager.GetString("CrucibleStatusBoard0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: battle with {1} (panel needs: {2})..
        /// </summary>
        internal static string CrucibleStatusBattle0And1And2 {
            get {
                return ResourceManager.GetString("CrucibleStatusBattle0And1And2", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Crucible auto-targeting.
        /// </summary>
        internal static string CrucibleTargeting {
            get {
                return ResourceManager.GetString("CrucibleTargeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Auto-Rotation targeting on a Crucible board: never picks zu eggs or morp....
        /// </summary>
        internal static string CrucibleTargetingDesc {
            get {
                return ResourceManager.GetString("CrucibleTargetingDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beast picks.
        /// </summary>
        internal static string CrucibleAdvisorHeader {
            get {
                return ResourceManager.GetString("CrucibleAdvisorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board.
        /// </summary>
        internal static string CrucibleAdvisorBoard {
            get {
                return ResourceManager.GetString("CrucibleAdvisorBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The captured familiar list has not arrived yet (open the Master's Bestiary on....
        /// </summary>
        internal static string CrucibleAdvisorRosterUnknown {
            get {
                return ResourceManager.GetString("CrucibleAdvisorRosterUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roster (familiars in the most battles' picks, number of battles): {0}.
        /// </summary>
        internal static string CrucibleAdvisorRoster0 {
            get {
                return ResourceManager.GetString("CrucibleAdvisorRoster0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to boss.
        /// </summary>
        internal static string CrucibleAdvisorBoss {
            get {
                return ResourceManager.GetString("CrucibleAdvisorBoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to elite.
        /// </summary>
        internal static string CrucibleAdvisorElite {
            get {
                return ResourceManager.GetString("CrucibleAdvisorElite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enemy.
        /// </summary>
        internal static string CrucibleAdvisorEnemy {
            get {
                return ResourceManager.GetString("CrucibleAdvisorEnemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to random space.
        /// </summary>
        internal static string CrucibleAdvisorRandom {
            get {
                return ResourceManager.GetString("CrucibleAdvisorRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enemy panel calls for: {0}.
        /// </summary>
        internal static string CrucibleAdvisorNeeds0 {
            get {
                return ResourceManager.GetString("CrucibleAdvisorNeeds0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worth capturing:.
        /// </summary>
        internal static string CrucibleAdvisorCapture {
            get {
                return ResourceManager.GetString("CrucibleAdvisorCapture", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Score mode (the character tanks).
        /// </summary>
        internal static string CrucibleScoreMode {
            get {
                return ResourceManager.GetString("CrucibleScoreMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For high-score runs: Challenge whenever the target turns on the familiar so f....
        /// </summary>
        internal static string CrucibleScoreModeDesc {
            get {
                return ResourceManager.GetString("CrucibleScoreModeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodge known tankbusters with {0} then {1}.
        /// </summary>
        internal static string CrucibleSnarlParting0And1 {
            get {
                return ResourceManager.GetString("CrucibleSnarlParting0And1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off by default. The familiar takes the aggro with Snarl, then Parting Blow se....
        /// </summary>
        internal static string CrucibleSnarlPartingDesc {
            get {
                return ResourceManager.GetString("CrucibleSnarlPartingDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parting Blow this many tenths of a second before the cast ends.
        /// </summary>
        internal static string CrucibleSnarlPartingLead {
            get {
                return ResourceManager.GetString("CrucibleSnarlPartingLead", resourceCulture);
            }
        }
    }
}
