//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GluttonyCombo.Resources.Localization.JobConfigs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BST_Config {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BST_Config() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GluttonyCombo.Resources.Localization.JobConfigs.BST_Config", typeof(BST_Config).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always slot 1.
        /// </summary>
        internal static string AlwaysSlot1 {
            get {
                return ResourceManager.GetString("AlwaysSlot1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always summons the familiar assigned to the first Battlehorn slot..
        /// </summary>
        internal static string AlwaysSlot1Desc {
            get {
                return ResourceManager.GetString("AlwaysSlot1Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always slot 2.
        /// </summary>
        internal static string AlwaysSlot2 {
            get {
                return ResourceManager.GetString("AlwaysSlot2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always summons the familiar assigned to the second Battlehorn slot..
        /// </summary>
        internal static string AlwaysSlot2Desc {
            get {
                return ResourceManager.GetString("AlwaysSlot2Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always slot 3.
        /// </summary>
        internal static string AlwaysSlot3 {
            get {
                return ResourceManager.GetString("AlwaysSlot3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always summons the familiar assigned to the third Battlehorn slot..
        /// </summary>
        internal static string AlwaysSlot3Desc {
            get {
                return ResourceManager.GetString("AlwaysSlot3Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Battlehorn slot order.
        /// </summary>
        internal static string AutoBattlehornSlotOrder {
            get {
                return ResourceManager.GetString("AutoBattlehornSlotOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold {0} for {1}.
        /// </summary>
        internal static string Hold0For1 {
            get {
                return ResourceManager.GetString("Hold0For1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waits for {0} (from {1}, 1500 potency {2}) before retreating the familiar, instead of retreating the moment its TP is spent (1000 potency)..
        /// </summary>
        internal static string Hold0For1Desc {
            get {
                return ResourceManager.GetString("Hold0For1Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include familiar mitigation {0}.
        /// </summary>
        internal static string IncludeFamiliarMitigation0 {
            get {
                return ResourceManager.GetString("IncludeFamiliarMitigation0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uses Beastskin/Vileskin/Scaleskin ({0} mitigation variants) automatically when player HP drops to 80% or below. Off by default..
        /// </summary>
        internal static string IncludeFamiliarMitigation0Desc {
            get {
                return ResourceManager.GetString("IncludeFamiliarMitigation0Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate 1 -&gt; 2 -&gt; 3.
        /// </summary>
        internal static string Rotate123 {
            get {
                return ResourceManager.GetString("Rotate123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotates through all three Battlehorn slots so each fresh summon re-arms {0} and {1}..
        /// </summary>
        internal static string Rotate123Desc {
            get {
                return ResourceManager.GetString("Rotate123Desc", resourceCulture);
            }
        }
    }
}
