//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GluttonyCombo.Resources.Localization.JobConfigs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BST_Config {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BST_Config() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GluttonyCombo.Resources.Localization.JobConfigs.BST_Config", typeof(BST_Config).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow knockback / draw-in {0}.
        /// </summary>
        internal static string AllowDisplacingRelease0 {
            get {
                return ResourceManager.GetString("AllowDisplacingRelease0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puk, diremite and treant knock enemies back; gigantoad and rotting goobbue dr....
        /// </summary>
        internal static string AllowDisplacingReleaseDesc {
            get {
                return ResourceManager.GetString("AllowDisplacingReleaseDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow cycling into no familiar.
        /// </summary>
        internal static string AllowPetlessCycling {
            get {
                return ResourceManager.GetString("AllowPetlessCycling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off (recommended): a familiar only retreats when another assigned Battlehorn ....
        /// </summary>
        internal static string AllowPetlessCyclingDesc {
            get {
                return ResourceManager.GetString("AllowPetlessCyclingDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow sleep {0} (lamb Lullaby).
        /// </summary>
        internal static string AllowSleepRelease0 {
            get {
                return ResourceManager.GetString("AllowSleepRelease0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lullaby puts enemies to sleep, which breaks on damage. Off (recommended): lam....
        /// </summary>
        internal static string AllowSleepReleaseDesc {
            get {
                return ResourceManager.GetString("AllowSleepReleaseDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use {0} while {1} is recasting.
        /// </summary>
        internal static string BorrowWhileReleaseRecasts0 {
            get {
                return ResourceManager.GetString("BorrowWhileReleaseRecasts0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levels 22-29: summoning does not reset the Tempered Release recast yet. On: a....
        /// </summary>
        internal static string BorrowWhileReleaseRecastsDesc {
            get {
                return ResourceManager.GetString("BorrowWhileReleaseRecastsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use wespe's Final Sting as its exit.
        /// </summary>
        internal static string FinalStingAsExit {
            get {
                return ResourceManager.GetString("FinalStingAsExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wespe's {0} skill (Final Sting) makes it retreat. On: it fires only as the we....
        /// </summary>
        internal static string FinalStingAsExitDesc {
            get {
                return ResourceManager.GetString("FinalStingAsExitDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum seconds a familiar fights before {0}.
        /// </summary>
        internal static string MinFamiliarStay0 {
            get {
                return ResourceManager.GetString("MinFamiliarStay0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh One with Nature between pulls.
        /// </summary>
        internal static string RefreshBetweenPulls {
            get {
                return ResourceManager.GetString("RefreshBetweenPulls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From level 18, out of combat with an enemy targeted: when the current familia....
        /// </summary>
        internal static string RefreshBetweenPullsDesc {
            get {
                return ResourceManager.GetString("RefreshBetweenPullsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (after Borrow, level 22+).
        /// </summary>
        internal static string SectionBeastMode0 {
            get {
                return ResourceManager.GetString("SectionBeastMode0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Familiar handling.
        /// </summary>
        internal static string SectionFamiliar {
            get {
                return ResourceManager.GetString("SectionFamiliar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string SectionOther {
            get {
                return ResourceManager.GetString("SectionOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summon a familiar when a hostile target is selected.
        /// </summary>
        internal static string SummonBeforeCombat {
            get {
                return ResourceManager.GetString("SummonBeforeCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of combat, summoning costs no lockout. Summons the first ready horn when ....
        /// </summary>
        internal static string SummonBeforeCombatDesc {
            get {
                return ResourceManager.GetString("SummonBeforeCombatDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In combat, on cooldown: less physical damage taken and higher critical hit ra....
        /// </summary>
        internal static string UseBeastskinDesc {
            get {
                return ResourceManager.GetString("UseBeastskinDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is a GCD spell: only when the target is out of melee range (up to 30 yalms....
        /// </summary>
        internal static string UseQuellingWaveRangedDesc {
            get {
                return ResourceManager.GetString("UseQuellingWaveRangedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use {0} and {1}.
        /// </summary>
        internal static string UseRally0And1 {
            get {
                return ResourceManager.GetString("UseRally0And1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rally at 3 Mastered Instinct right after the axe that granted the third. Rall....
        /// </summary>
        internal static string UseRallyDesc {
            get {
                return ResourceManager.GetString("UseRallyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When an enemy is targeting the character. Off by default: the barrier only pa....
        /// </summary>
        internal static string UseScaleskinDesc {
            get {
                return ResourceManager.GetString("UseScaleskinDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When an enemy is within 6 yalms..
        /// </summary>
        internal static string UseSeedsowerDesc {
            get {
                return ResourceManager.GetString("UseSeedsowerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As a gap closer when the target is 4-20 yalms away, and for damage in melee r....
        /// </summary>
        internal static string UseShieldChargeDesc {
            get {
                return ResourceManager.GetString("UseShieldChargeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only to interrupt an interruptible cast in melee range..
        /// </summary>
        internal static string UseSoulCrushDesc {
            get {
                return ResourceManager.GetString("UseSoulCrushDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When an enemy is targeting the character..
        /// </summary>
        internal static string UseVileskinDesc {
            get {
                return ResourceManager.GetString("UseVileskinDesc", resourceCulture);
            }
        }
    }
}
