<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>0.0.2.5</Version>
    <AssemblyName>LazySightseeing</AssemblyName>
    <Description>Fully automated sightseeing log completions utilizing vnavmesh and lifestream.</Description>
    <IsPackable>false</IsPackable>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <SupportedOSPlatformVersion>8.0</SupportedOSPlatformVersion>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Author>dajoey</Author>
    <Name>Lazy Sightseeing</Name>
    <InternalName>LazySightseeing</InternalName>
    <Punchline>Auto-navigate and complete sightseeing log vistas using vnavmesh and lifestream</Punchline>
    <ApplicableVersion>any</ApplicableVersion>
    <Tags>sightseeing;automation;navigation;vnavmesh</Tags>
    <CategoryTags>utility</CategoryTags>
    <DalamudApiLevel>15</DalamudApiLevel>
    <LoadRequiredState>0</LoadRequiredState>
    <LoadSync>false</LoadSync>
    <CanUnloadAsync>false</CanUnloadAsync>
    <LoadPriority>0</LoadPriority>
    <AcceptsFeedback>false</AcceptsFeedback>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="LazySightseeing.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ECommons" Version="3.2.0.9" />
  </ItemGroup>

  <Target Name="PruneOutputDlls" AfterTargets="ResolveReferences">
    <ItemGroup>
      <_KeepDlls Include="@(ReferenceCopyLocalPaths)" Condition="
          '%(Filename)' == 'LazySightseeing' or
          '%(Filename)' == 'ECommons'
        " />
      <ReferenceCopyLocalPaths Remove="@(ReferenceCopyLocalPaths)" />
      <ReferenceCopyLocalPaths Include="@(_KeepDlls)" />
    </ItemGroup>
  </Target>
</Project>
