#!/usr/bin/env python3
"""Generate BST_CrucibleData.Generated.cs from crucible_sheets_7.56.json.

The JSON is the Crucible of the Unbroken slice of the FFXIV 7.56 game sheets (XBMContent,
XBMContentBattle, XBMBattleDetail, XBMBattleDetailAction, BNpcName, BNpcResist, Action, Status),
pulled from xivapi v2 and decoded on 2026-09-16:
  - XBMBattleDetail.Element is the enemy's weakness (1 Fire .. 9 Slashing).
  - BNpcResist bits (Slow, Petrify, Paralysis, Interrupt, Blind, Poison, Stun, Sleep, Bind, Heavy, Doom):
    '1' = immune, '0' = vulnerable.
  - interruptible = Action column after PreservesCombo (matches every guide-confirmed interrupt).
  - dispellable enemy buff = beneficial Status with its Unknown8 flag set (CanDispel is false on all of them).
  - cleansable debuff = detrimental Status with CanDispel.

Usage: python3 tools/bst-crucible/gen_crucible_data.py
Writes src/Shared/LalaCrucible/BST_CrucibleData.Generated.cs (shared SOURCE: GluttonyCombo + LazyCrucible).
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
SRC = os.path.join(HERE, "crucible_sheets_7.56.json")
BEASTS = os.path.join(HERE, "crucible_beasts_7.56.json")
OUT = os.path.join(REPO, "src", "Shared", "LalaCrucible", "BST_CrucibleData.Generated.cs")

WEAKNESS = {0: "None", 1: "Fire", 2: "Wind", 3: "Earth", 4: "Lightning", 5: "Ice", 6: "Water", 7: "Blunt", 8: "Piercing", 9: "Slashing"}


def cs_string(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    data = json.load(open(SRC, encoding="utf-8"))
    extra = json.load(open(BEASTS, encoding="utf-8"))
    stars = extra["enemy_stars"]
    lines = []
    w = lines.append
    w("// <auto-generated>")
    w("// GENERATED by tools/bst-crucible/gen_crucible_data.py from tools/bst-crucible/crucible_sheets_7.56.json.")
    w("// Do not edit by hand: change the generator or the sheet slice and re-run it.")
    w("// Source: " + data["source"])
    w("// </auto-generated>")
    w("")
    w("namespace Lalalazy.Crucible;")
    w("")
    w("internal static partial class BST_CrucibleData")
    w("{")

    w("    /// <summary> The five boards: XBMContent rows 1-5. </summary>")
    w("    public static readonly CrucibleBoard[] Boards =")
    w("    [")
    for b in data["boards"]:
        w(f"        new({b['board']}, {b['territory']}, {b['cfc']}, {b['level']}, {b['item_level']}, {b['beast_rank']}, {b['roster']}, {len(b['battles'])}, {cs_string(b['name'])}),")
    w("    ];")
    w("")

    interruptible, dispellable, cleansable, hits = set(), set(), set(), set()
    w("    /// <summary> Every enemy on every board's panel (XBMBattleDetail), keyed by BNpcName. Battle 0 is the boss fight. </summary>")
    w("    public static readonly CrucibleEnemy[] Enemies =")
    w("    [")
    count = 0
    for b in data["boards"]:
        for bat in b["battles"]:
            for e in bat["enemies"]:
                needs = []
                for a in e["actions"]:
                    st = a["status"]
                    if a["interruptible"]:
                        needs.append("Interrupt")
                        interruptible.add(a["action"])
                    if st and st["category"] == "beneficial" and st["dispellable"]:
                        needs.append("Dispel")
                        dispellable.add(st["id"])
                    if st and st["category"] == "detrimental" and st["cleansable"]:
                        needs.append("Cleanse")
                        cleansable.add(st["id"])
                    if a["area"] == "Single Target" and a["target"] in ("Player", "Highest Enmity"):
                        hits.add(a["action"])
                needs_cs = " | ".join(f"CrucibleNeeds.{n}" for n in sorted(set(needs))) or "CrucibleNeeds.None"
                vuln = 0
                for i, bit in enumerate(e["resist_bits"]):
                    if bit == "0":
                        vuln |= 1 << i
                st = stars[str(e["name_id"])]
                packed = (st[0] << 12) | (st[1] << 9) | (st[2] << 6) | (st[3] << 3) | st[4]
                w(f"        new({e['name_id']}, {b['board']}, {bat['battle']}, {e['sub']}, CrucibleWeakness.{WEAKNESS[e['weakness']]}, 0x{vuln:03x}, {needs_cs}, 0x{packed:04x}, {cs_string(e['name'])}),")
                count += 1
    w("    ];")
    w("")
    w(f"    public const int EnemyCount = {count};")
    w(f"    public const int BattleCount = {sum(len(b['battles']) for b in data['boards'])};")
    w("")

    def ids(name, values, doc):
        w(f"    /// <summary> {doc} </summary>")
        w(f"    public static readonly uint[] {name} = [{', '.join(str(v) for v in sorted(values))}];")
        w("")

    w("    /// <summary> Battle role from the board layout (XBMContentStageEvent node type) and whether only a random space leads to it. </summary>")
    w("    public static readonly CrucibleBattleInfo[] Battles =")
    w("    [")
    for key, info in sorted(extra["battle_roles"].items(), key=lambda kv: (int(kv[0].split(":")[0]), int(kv[0].split(":")[1]))):
        board, battle = key.split(":")
        w(f"        new({board}, {battle}, CrucibleRole.{info['role'].replace(' ', '')}, {'true' if info['random_only'] else 'false'}),")
    w("    ];")
    w("")
    w("    /// <summary>")
    w("    ///     Familiar profiles (XBMPet): auto-attack element as a panel weakness, whether it is magic, the statuses its")
    w("    ///     skills inflict (same bits as <see cref=\"CrucibleEnemy.Vulnerable\"/>), and STR/INT/PHY R/MAG R/CON at beast")
    w("    ///     ranks 5/10/15/20/25 (the five boards' rank sync), flattened rank-first. Index 0 is unused.")
    w("    /// </summary>")
    w("    public static readonly CrucibleBeastProfile[] BeastProfiles =")
    w("    [")
    w("        default,")
    for bst in extra["beasts"]:
        flat = ", ".join(str(v) for rank in ("5", "10", "15", "20", "25") for v in bst["stats"][rank])
        w(f"        new({bst['row']}, CrucibleWeakness.{WEAKNESS[bst['auto_element']]}, {'true' if bst['auto_magic'] else 'false'}, 0x{bst['inflicts']:03x}, [{flat}]),")
    w("    ];")
    w("")
    ids("PanelInterruptibleActions", interruptible, "Panel casts flagged interruptible.")
    ids("PanelDispellableBuffs", dispellable, "Enemy buffs from panel casts that carry the dispellable flag.")
    ids("PanelCleansableDebuffs", cleansable, "Debuffs from panel casts that can be cleansed.")
    ids("PanelSingleTargetHits", hits, "Panel casts aimed at the player or the highest-enmity target as a single-target hit.")
    lines[-1:] = []
    w("}")
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {OUT}: {count} enemies")


if __name__ == "__main__":
    main()
