#!/usr/bin/env python3
"""Guide counters -> shared C# table (src/Shared/LalaCrucible/BST_CrucibleGuideNeeds.Generated.cs).

LazyCrucible reads the fight guide JSON; GluttonyCombo has no guide file, so the same ability needs (interrupt, dispel,
cleanse, each with its Required / Useful tier) ship to it as generated shared source. The tier rule is
GuideCounter.Tier in src/LazyCrucible/Guide/CrucibleGuide.cs; the LazyCrucible harness asserts that this table equals
CrucibleGuide.NeedsOf for every battle, so a drift in either place fails a release gate.

Usage: python3 tools/crucible-planner/gen_guide_needs.py [--check]
"""
import json
import os
import sys

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
GUIDE = os.path.join(REPO, "src", "LazyCrucible", "Guide", "CrucibleGuide.json")
OUT = os.path.join(REPO, "src", "Shared", "LalaCrucible", "BST_CrucibleGuideNeeds.Generated.cs")
KINDS = {"interrupt": "Interrupt", "dispel": "Dispel", "cleanse": "Cleanse"}


def tier(c):
    src = c.get("src", [])
    if "panel" in src or c.get("mandatory"):
        return "Required"
    if c.get("disputed"):
        return "Useful"
    return "Required" if len({s.split(":")[0] for s in src}) >= 2 else "Useful"


def literal(text):
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render():
    guide = json.load(open(GUIDE, encoding="utf-8"))
    rows = []
    for f in guide["fights"]:
        for c in f.get("counters", []):
            kind = KINDS.get(c["need"])
            if kind is None:
                continue
            src = ", ".join(literal(s) for s in c.get("src", []))
            rows.append(f"        new({f['board']}, {f['battle']}, CrucibleNeeds.{kind}, CrucibleNeedTier.{tier(c)}, "
                        f"{literal(c.get('what', ''))}, [{src}]),")
    lines = [
        "// <auto-generated>",
        "//   tools/crucible-planner/gen_guide_needs.py from src/LazyCrucible/Guide/CrucibleGuide.json. Do not edit by hand:",
        "//   edit the guide, regenerate, and the LazyCrucible harness checks the table equals CrucibleGuide.NeedsOf.",
        "// </auto-generated>",
        "using System.Collections.Generic;",
        "",
        "namespace Lalalazy.Crucible;",
        "",
        "internal static partial class BST_CrucibleGuideNeeds",
        "{",
        "    /// <summary> Every fight guide counter that is an interrupt, dispel or cleanse, in guide order. </summary>",
        "    private static readonly GuideNeedRow[] Rows =",
        "    [",
        *rows,
        "    ];",
        "}",
        "",
    ]
    return "\n".join(lines)


def main():
    text = render()
    if "--check" in sys.argv:
        current = open(OUT, encoding="utf-8", newline="").read().replace("\r\n", "\n") if os.path.exists(OUT) else ""
        if current != text:
            sys.exit("BST_CrucibleGuideNeeds.Generated.cs is stale: run tools/crucible-planner/gen_guide_needs.py")
        print("OK  guide needs table is current")
        return
    with open(OUT, "w", encoding="utf-8", newline="") as fh:
        fh.write(text)
    print(f"wrote {OUT} ({text.count('new(')} rows)")


if __name__ == "__main__":
    main()
