// <auto-generated>
// GENERATED by tools/bst-crucible/gen_crucible_data.py from tools/bst-crucible/crucible_sheets_7.56.json.
// Do not edit by hand: change the generator or the sheet slice and re-run it.
// Source: FFXIV 7.56 game sheets via xivapi v2 (version f5af21155b99a524): XBMContent, XBMContentBattle, XBMBattleDetail, XBMBattleDetailAction, BNpcName, BNpcResist, Action, Status. Decoded 2026-09-16.
// </auto-generated>

namespace GluttonyCombo.Combos.PvE;

internal static partial class BST_CrucibleData
{
    /// <summary> The five boards: XBMContent rows 1-5. </summary>
    public static readonly CrucibleBoard[] Boards =
    [
        new(1, 1339, 1088, 30, 0, 5, 10, 6, "First Board of the Unbroken"),
        new(2, 1340, 1089, 40, 0, 10, 12, 7, "Second Board of the Unbroken"),
        new(3, 1341, 1090, 50, 100, 15, 14, 8, "Third Board of the Unbroken"),
        new(4, 1342, 1091, 50, 120, 20, 12, 10, "First Master's Board"),
        new(5, 1343, 1092, 50, 135, 25, 15, 14, "Second Master's Board"),
    ];

    /// <summary> Every enemy on every board's panel (XBMBattleDetail), keyed by BNpcName. Battle 0 is the boss fight. </summary>
    public static readonly CrucibleEnemy[] Enemies =
    [
        new(14541, 1, 0, 0, CrucibleWeakness.Piercing, 0x000, CrucibleNeeds.Cleanse, "Pas de Seul"),
        new(14542, 1, 0, 1, CrucibleWeakness.Fire, 0x409, CrucibleNeeds.Dispel | CrucibleNeeds.Interrupt, "succubus mage"),
        new(14543, 1, 0, 2, CrucibleWeakness.Fire, 0x4c7, CrucibleNeeds.None, "succubus knight"),
        new(14531, 1, 1, 0, CrucibleWeakness.Blunt, 0x009, CrucibleNeeds.Dispel | CrucibleNeeds.Interrupt, "bone knight"),
        new(14532, 1, 1, 1, CrucibleWeakness.Blunt, 0x200, CrucibleNeeds.Cleanse, "bone bishop"),
        new(14533, 1, 2, 0, CrucibleWeakness.Lightning, 0x020, CrucibleNeeds.None, "arch demon piece"),
        new(14535, 1, 3, 0, CrucibleWeakness.Slashing, 0x220, CrucibleNeeds.Dispel, "piscodemon piece"),
        new(14536, 1, 4, 0, CrucibleWeakness.Ice, 0x010, CrucibleNeeds.Cleanse, "banemite piece"),
        new(14537, 1, 4, 1, CrucibleWeakness.Ice, 0x7d7, CrucibleNeeds.None, "miteling piece"),
        new(14538, 1, 5, 0, CrucibleWeakness.Wind, 0x030, CrucibleNeeds.None, "ogre piece"),
        new(14539, 1, 5, 1, CrucibleWeakness.Water, 0x300, CrucibleNeeds.None, "wisp piece"),
        new(14748, 1, 5, 2, CrucibleWeakness.Water, 0x300, CrucibleNeeds.None, "great wisp piece"),
        new(14561, 2, 0, 0, CrucibleWeakness.Blunt, 0x030, CrucibleNeeds.Dispel, "Loosefrox Inkyjots"),
        new(14562, 2, 0, 1, CrucibleWeakness.Water, 0x000, CrucibleNeeds.Cleanse, "Chewchum Popoto"),
        new(14545, 2, 1, 0, CrucibleWeakness.Wind, 0x020, CrucibleNeeds.None, "manticore piece"),
        new(14546, 2, 2, 0, CrucibleWeakness.Piercing, 0x000, CrucibleNeeds.None, "taurus piece"),
        new(14548, 2, 2, 1, CrucibleWeakness.Ice, 0x0d5, CrucibleNeeds.None, "ahriman piece"),
        new(14549, 2, 3, 0, CrucibleWeakness.Lightning, 0x030, CrucibleNeeds.None, "wyvern piece"),
        new(14552, 2, 4, 0, CrucibleWeakness.Earth, 0x000, CrucibleNeeds.None, "voidmancer piece"),
        new(14553, 2, 4, 1, CrucibleWeakness.Ice, 0x703, CrucibleNeeds.None, "zombie piece"),
        new(14555, 2, 5, 0, CrucibleWeakness.Fire, 0x000, CrucibleNeeds.None, "elder tablitaur piece"),
        new(14556, 2, 5, 1, CrucibleWeakness.Fire, 0x238, CrucibleNeeds.Dispel | CrucibleNeeds.Interrupt, "younger tablitaur piece"),
        new(14557, 2, 6, 0, CrucibleWeakness.Slashing, 0x7c7, CrucibleNeeds.Cleanse, "demon piece"),
        new(14558, 2, 6, 1, CrucibleWeakness.Ice, 0x7c7, CrucibleNeeds.None, "evil weapon piece"),
        new(14559, 2, 6, 2, CrucibleWeakness.Earth, 0x445, CrucibleNeeds.None, "devilet piece"),
        new(14592, 3, 0, 0, CrucibleWeakness.None, 0x020, CrucibleNeeds.None, "Guttler the Gutter"),
        new(14595, 3, 0, 1, CrucibleWeakness.Lightning, 0x043, CrucibleNeeds.None, "Thanatos piece"),
        new(14564, 3, 1, 0, CrucibleWeakness.Fire, 0x020, CrucibleNeeds.None, "cavalier piece"),
        new(14567, 3, 1, 1, CrucibleWeakness.Blunt, 0x147, CrucibleNeeds.None, "bone bishop"),
        new(14569, 3, 2, 0, CrucibleWeakness.Ice, 0x160, CrucibleNeeds.None, "ymir piece"),
        new(14571, 3, 2, 1, CrucibleWeakness.Blunt, 0x018, CrucibleNeeds.Interrupt, "Sahagin piece"),
        new(14572, 3, 3, 0, CrucibleWeakness.Earth, 0x030, CrucibleNeeds.None, "zu piece"),
        new(14573, 3, 3, 1, CrucibleWeakness.Blunt, 0x7f7, CrucibleNeeds.None, "cockerel piece"),
        new(14574, 3, 3, 2, CrucibleWeakness.Blunt, 0x4fb, CrucibleNeeds.Interrupt, "pullet piece"),
        new(14577, 3, 4, 0, CrucibleWeakness.Wind, 0x020, CrucibleNeeds.None, "catoblepas piece"),
        new(14580, 3, 5, 0, CrucibleWeakness.Water, 0x000, CrucibleNeeds.None, "Lakhamu piece"),
        new(14581, 3, 5, 1, CrucibleWeakness.Water, 0x4c1, CrucibleNeeds.None, "golem piece"),
        new(14583, 3, 6, 0, CrucibleWeakness.Piercing, 0x020, CrucibleNeeds.None, "siren piece"),
        new(14585, 3, 6, 1, CrucibleWeakness.Fire, 0x305, CrucibleNeeds.None, "shambling piece"),
        new(14586, 3, 6, 2, CrucibleWeakness.Fire, 0x000, CrucibleNeeds.None, "crawling piece"),
        new(14587, 3, 7, 0, CrucibleWeakness.Lightning, 0x200, CrucibleNeeds.None, "campeador piece"),
        new(14588, 3, 7, 1, CrucibleWeakness.Lightning, 0x707, CrucibleNeeds.None, "sabotender piece"),
        new(14589, 3, 7, 2, CrucibleWeakness.Lightning, 0x707, CrucibleNeeds.None, "flowertender piece"),
        new(14590, 3, 7, 3, CrucibleWeakness.Lightning, 0x707, CrucibleNeeds.None, "soldado piece"),
        new(14591, 3, 7, 4, CrucibleWeakness.Ice, 0x000, CrucibleNeeds.None, "guardia piece"),
        new(14628, 4, 0, 0, CrucibleWeakness.Earth, 0x000, CrucibleNeeds.None, "Borgny the Venomous"),
        new(14629, 4, 0, 1, CrucibleWeakness.Water, 0x741, CrucibleNeeds.None, "toxic mass"),
        new(14596, 4, 1, 0, CrucibleWeakness.Piercing, 0x220, CrucibleNeeds.Dispel, "Strix piece"),
        new(14599, 4, 2, 0, CrucibleWeakness.Slashing, 0x000, CrucibleNeeds.Cleanse, "morbol piece"),
        new(14600, 4, 2, 1, CrucibleWeakness.Slashing, 0x3c3, CrucibleNeeds.Cleanse, "seedling piece"),
        new(14601, 4, 2, 2, CrucibleWeakness.Slashing, 0x441, CrucibleNeeds.None, "ochu piece"),
        new(14602, 4, 2, 3, CrucibleWeakness.Ice, 0x200, CrucibleNeeds.Cleanse, "carrion broth"),
        new(14603, 4, 3, 0, CrucibleWeakness.Wind, 0x010, CrucibleNeeds.None, "corpse flower piece"),
        new(14605, 4, 3, 1, CrucibleWeakness.Blunt, 0x4d5, CrucibleNeeds.None, "queen hawk piece"),
        new(14606, 4, 4, 0, CrucibleWeakness.Fire, 0x030, CrucibleNeeds.None, "ice dragon piece"),
        new(14607, 4, 4, 1, CrucibleWeakness.Fire, 0x041, CrucibleNeeds.None, "ice sprite"),
        new(14608, 4, 5, 0, CrucibleWeakness.None, 0x000, CrucibleNeeds.None, "gargoyle piece"),
        new(14610, 4, 6, 0, CrucibleWeakness.Lightning, 0x008, CrucibleNeeds.Interrupt, "administrator piece"),
        new(14611, 4, 6, 1, CrucibleWeakness.Lightning, 0x340, CrucibleNeeds.None, "bug piece"),
        new(14612, 4, 6, 2, CrucibleWeakness.Lightning, 0x341, CrucibleNeeds.None, "footman piece"),
        new(14613, 4, 6, 3, CrucibleWeakness.Lightning, 0x341, CrucibleNeeds.None, "dreadnaught piece"),
        new(14614, 4, 6, 4, CrucibleWeakness.Lightning, 0x341, CrucibleNeeds.None, "drone piece"),
        new(14616, 4, 6, 5, CrucibleWeakness.Piercing, 0x341, CrucibleNeeds.Cleanse, "cobra piece"),
        new(14617, 4, 7, 0, CrucibleWeakness.Water, 0x000, CrucibleNeeds.None, "golem piece"),
        new(14618, 4, 8, 0, CrucibleWeakness.Blunt, 0x230, CrucibleNeeds.None, "treant piece"),
        new(14619, 4, 8, 1, CrucibleWeakness.Blunt, 0x7f7, CrucibleNeeds.None, "slug piece"),
        new(14620, 4, 8, 2, CrucibleWeakness.Blunt, 0x431, CrucibleNeeds.None, "sapling piece"),
        new(14621, 4, 8, 3, CrucibleWeakness.Ice, 0x7d7, CrucibleNeeds.None, "diremite piece"),
        new(14622, 4, 8, 4, CrucibleWeakness.Ice, 0x429, CrucibleNeeds.Interrupt, "biloko piece"),
        new(14623, 4, 9, 0, CrucibleWeakness.Wind, 0x008, CrucibleNeeds.Interrupt, "Progenitrix piece"),
        new(14624, 4, 9, 1, CrucibleWeakness.Wind, 0x441, CrucibleNeeds.None, "grenade piece"),
        new(14625, 4, 9, 2, CrucibleWeakness.Wind, 0x441, CrucibleNeeds.None, "bomb piece"),
        new(14626, 4, 9, 3, CrucibleWeakness.Fire, 0x441, CrucibleNeeds.Dispel, "snoll piece"),
        new(14627, 4, 9, 4, CrucibleWeakness.Water, 0x400, CrucibleNeeds.Cleanse, "pyrobolus piece"),
        new(14693, 5, 0, 0, CrucibleWeakness.None, 0x020, CrucibleNeeds.None, "Lauda the Spellcleaver"),
        new(14699, 5, 0, 1, CrucibleWeakness.Lightning, 0x043, CrucibleNeeds.None, "Thanatos piece"),
        new(14631, 5, 1, 0, CrucibleWeakness.Earth, 0x220, CrucibleNeeds.Cleanse, "Flauros piece"),
        new(14632, 5, 1, 1, CrucibleWeakness.Earth, 0x001, CrucibleNeeds.None, "lightning sprite"),
        new(14633, 5, 2, 0, CrucibleWeakness.Slashing, 0x220, CrucibleNeeds.Cleanse, "mindflayer piece"),
        new(14634, 5, 2, 1, CrucibleWeakness.Water, 0x731, CrucibleNeeds.Cleanse, "myconid piece"),
        new(14638, 5, 3, 0, CrucibleWeakness.Ice, 0x220, CrucibleNeeds.None, "boogyman piece"),
        new(14639, 5, 3, 1, CrucibleWeakness.Wind, 0x7f5, CrucibleNeeds.None, "deepeye piece"),
        new(14640, 5, 3, 2, CrucibleWeakness.Wind, 0x440, CrucibleNeeds.None, "bomb piece"),
        new(14641, 5, 3, 3, CrucibleWeakness.None, 0x001, CrucibleNeeds.None, "light sprite"),
        new(14642, 5, 4, 0, CrucibleWeakness.Blunt, 0x000, CrucibleNeeds.None, "Atomos piece"),
        new(14643, 5, 4, 1, CrucibleWeakness.Piercing, 0x7f7, CrucibleNeeds.None, "red gremlin piece"),
        new(14644, 5, 4, 2, CrucibleWeakness.Piercing, 0x7f7, CrucibleNeeds.None, "gremlin piece"),
        new(14645, 5, 4, 3, CrucibleWeakness.Wind, 0x420, CrucibleNeeds.None, "pudding piece"),
        new(14646, 5, 4, 4, CrucibleWeakness.Lightning, 0x420, CrucibleNeeds.None, "bavarois piece"),
        new(14647, 5, 4, 5, CrucibleWeakness.Earth, 0x420, CrucibleNeeds.None, "flan piece"),
        new(14648, 5, 4, 6, CrucibleWeakness.Piercing, 0x707, CrucibleNeeds.None, "vodoriga piece"),
        new(14649, 5, 4, 7, CrucibleWeakness.Ice, 0x020, CrucibleNeeds.None, "menacing dahak piece"),
        new(14651, 5, 5, 0, CrucibleWeakness.Wind, 0x030, CrucibleNeeds.Dispel, "drake piece"),
        new(14653, 5, 5, 1, CrucibleWeakness.Fire, 0x731, CrucibleNeeds.None, "barbmole piece"),
        new(14655, 5, 5, 2, CrucibleWeakness.Water, 0x430, CrucibleNeeds.None, "abaddon piece"),
        new(14656, 5, 5, 3, CrucibleWeakness.Blunt, 0x001, CrucibleNeeds.None, "morpho piece"),
        new(14657, 5, 6, 0, CrucibleWeakness.Fire, 0x010, CrucibleNeeds.None, "Durga piece"),
        new(14659, 5, 6, 1, CrucibleWeakness.Blunt, 0x041, CrucibleNeeds.None, "spinner-rook piece"),
        new(14660, 5, 7, 0, CrucibleWeakness.Piercing, 0x000, CrucibleNeeds.None, "medusa piece"),
        new(14661, 5, 7, 1, CrucibleWeakness.Piercing, 0x42c, CrucibleNeeds.Interrupt, "lamia piece"),
        new(14662, 5, 7, 2, CrucibleWeakness.None, 0x432, CrucibleNeeds.Cleanse, "cyclops piece"),
        new(14663, 5, 8, 0, CrucibleWeakness.Water, 0x000, CrucibleNeeds.Cleanse, "chimera piece"),
        new(14665, 5, 9, 0, CrucibleWeakness.Slashing, 0x000, CrucibleNeeds.None, "sphinx piece"),
        new(14670, 5, 10, 0, CrucibleWeakness.None, 0x230, CrucibleNeeds.None, "gigantis piece"),
        new(14671, 5, 10, 1, CrucibleWeakness.None, 0x63a, CrucibleNeeds.Cleanse | CrucibleNeeds.Interrupt, "cyclops piece"),
        new(14672, 5, 10, 2, CrucibleWeakness.Earth, 0x028, CrucibleNeeds.Interrupt, "congealed lightning"),
        new(14673, 5, 10, 3, CrucibleWeakness.Wind, 0x028, CrucibleNeeds.Interrupt, "congealed kindling"),
        new(14674, 5, 11, 0, CrucibleWeakness.Lightning, 0x4b7, CrucibleNeeds.None, "swordsmog piece"),
        new(14675, 5, 11, 1, CrucibleWeakness.Lightning, 0x030, CrucibleNeeds.None, "mogbreaker piece"),
        new(14676, 5, 11, 2, CrucibleWeakness.Blunt, 0x061, CrucibleNeeds.None, "kinged kupocurer"),
        new(14677, 5, 11, 3, CrucibleWeakness.Blunt, 0x061, CrucibleNeeds.None, "kinged kupocaster"),
        new(14678, 5, 11, 4, CrucibleWeakness.Blunt, 0x061, CrucibleNeeds.None, "kupocurer piece"),
        new(14679, 5, 11, 5, CrucibleWeakness.Blunt, 0x061, CrucibleNeeds.None, "kupocaster piece"),
        new(14680, 5, 11, 6, CrucibleWeakness.Lightning, 0x3f7, CrucibleNeeds.Dispel, "kinged swordsmog"),
        new(14681, 5, 11, 7, CrucibleWeakness.Water, 0x420, CrucibleNeeds.None, "melomog piece"),
        new(14683, 5, 11, 8, CrucibleWeakness.Water, 0x420, CrucibleNeeds.None, "mogmugger piece"),
        new(14684, 5, 12, 0, CrucibleWeakness.Earth, 0x020, CrucibleNeeds.None, "behemoth piece"),
        new(14685, 5, 12, 1, CrucibleWeakness.Lightning, 0x341, CrucibleNeeds.None, "giant piece"),
        new(14686, 5, 12, 2, CrucibleWeakness.Earth, 0x001, CrucibleNeeds.Cleanse, "lightning sprite"),
        new(14688, 5, 13, 0, CrucibleWeakness.Ice, 0x000, CrucibleNeeds.None, "king ahriman piece"),
        new(14691, 5, 13, 1, CrucibleWeakness.Wind, 0x330, CrucibleNeeds.Cleanse, "hapalit piece"),
        new(14692, 5, 13, 2, CrucibleWeakness.Ice, 0x4c1, CrucibleNeeds.None, "dirty eye piece"),
    ];

    public const int EnemyCount = 122;
    public const int BattleCount = 45;

    /// <summary> Panel casts flagged interruptible. </summary>
    public static readonly uint[] PanelInterruptibleActions = [46871, 46928, 48203, 48485, 48489, 48740, 48782, 48802, 49287, 49368, 49373, 49375];

    /// <summary> Enemy buffs from panel casts that carry the dispellable flag. </summary>
    public static readonly uint[] PanelDispellableBuffs = [1225, 2074, 2528, 5020, 5423, 5465];

    /// <summary> Debuffs from panel casts that can be cleansed. </summary>
    public static readonly uint[] PanelCleansableDebuffs = [4880, 5140, 5141, 5381, 5382, 5495, 5498, 5500];

    /// <summary> Panel casts aimed at the player or the highest-enmity target as a single-target hit. </summary>
    public static readonly uint[] PanelSingleTargetHits = [46906, 46920, 46935, 48138, 48247, 48489, 48563, 48568, 48621, 48626, 48680, 48689, 49189, 49213, 49241, 49254, 49260, 49399, 49435, 50544, 50747, 50750, 50793];
}
