// <auto-generated>
// GENERATED by tools/lazycrucible/gen_lazycrucible_data.py from tools/lazycrucible/crucible_items_boards_7.56.json.
// Do not edit by hand: change the generator or the sheet slice and re-run it.
// Source: FFXIV 7.56 game sheets via xivapi v2 (XBMItem, XBMPet (SatietyMax), XBMContentStageEvent, XBMContentStageEventMap, XBMContentCamp, XBMContentRandomStageEvent, XBMRandomStageEvent), decoded 2026-09-16 (crucible-data/build.py)
// </auto-generated>

namespace LazyCrucible;

internal static partial class CrucibleBoards
{
    /// <summary> Every board's spaces, index = board (0 unused); battle -1 = not a battle space. </summary>
    public static readonly CrucibleSpace[][] Spaces =
    [
        [],
        [
            new(0, SpaceType.Start, 0, -1, 0, null),
            new(1, SpaceType.Enemy, 1, 1, 0, null),
            new(2, SpaceType.Enemy, 2, 2, 0, null),
            new(3, SpaceType.Enemy, 2, 3, 0, null),
            new(4, SpaceType.Campsite, 3, -1, 2, null),
            new(5, SpaceType.Treasure, 3, -1, 0, null),
            new(6, SpaceType.Enemy, 4, 4, 0, null),
            new(7, SpaceType.Treasure, 5, -1, 0, null),
            new(8, SpaceType.Elite, 6, 5, 0, null),
            new(9, SpaceType.Treasure, 7, -1, 0, null),
            new(10, SpaceType.Campsite, 7, -1, 2, null),
            new(11, SpaceType.Shop, 8, -1, 0, null),
            new(12, SpaceType.Boss, 9, 0, 0, null),
        ],
        [
            new(0, SpaceType.Start, 0, -1, 0, null),
            new(1, SpaceType.Enemy, 1, 1, 0, null),
            new(2, SpaceType.Shop, 2, -1, 0, null),
            new(3, SpaceType.Elite, 3, 2, 0, null),
            new(4, SpaceType.Enemy, 3, 3, 0, null),
            new(5, SpaceType.Treasure, 4, -1, 0, null),
            new(6, SpaceType.Campsite, 4, -1, 2, null),
            new(7, SpaceType.Enemy, 5, 4, 0, null),
            new(8, SpaceType.Treasure, 6, -1, 0, null),
            new(9, SpaceType.Elite, 7, 5, 0, null),
            new(10, SpaceType.Random, 8, -1, 0, [new(SpaceType.Enemy, 6, 0), new(SpaceType.Campsite, -1, 3)]),
            new(11, SpaceType.Treasure, 8, -1, 0, null),
            new(12, SpaceType.Shop, 9, -1, 0, null),
            new(13, SpaceType.Boss, 10, 0, 0, null),
        ],
        [
            new(0, SpaceType.Start, 0, -1, 0, null),
            new(1, SpaceType.Enemy, 1, 1, 0, null),
            new(2, SpaceType.Enemy, 2, 2, 0, null),
            new(3, SpaceType.Shop, 3, -1, 0, null),
            new(4, SpaceType.Elite, 4, 3, 0, null),
            new(5, SpaceType.Enemy, 4, 4, 0, null),
            new(6, SpaceType.Treasure, 5, -1, 0, null),
            new(7, SpaceType.Campsite, 5, -1, 3, null),
            new(8, SpaceType.Enemy, 6, 5, 0, null),
            new(9, SpaceType.Treasure, 7, -1, 0, null),
            new(10, SpaceType.Shop, 7, -1, 0, null),
            new(11, SpaceType.Elite, 8, 6, 0, null),
            new(12, SpaceType.Treasure, 9, -1, 0, null),
            new(13, SpaceType.Random, 10, -1, 0, [new(SpaceType.Enemy, 7, 0), new(SpaceType.Treasure, -1, 0)]),
            new(14, SpaceType.Campsite, 10, -1, 3, null),
            new(15, SpaceType.Shop, 11, -1, 0, null),
            new(16, SpaceType.Boss, 12, 0, 0, null),
        ],
        [
            new(0, SpaceType.Start, 0, -1, 0, null),
            new(1, SpaceType.Enemy, 1, 1, 0, null),
            new(2, SpaceType.Enemy, 2, 2, 0, null),
            new(3, SpaceType.Random, 2, -1, 0, [new(SpaceType.Enemy, 3, 0), new(SpaceType.Treasure, -1, 0)]),
            new(4, SpaceType.Shop, 3, -1, 0, null),
            new(5, SpaceType.Campsite, 4, -1, 2, null),
            new(6, SpaceType.Random, 4, -1, 0, [new(SpaceType.Enemy, 4, 0), new(SpaceType.Treasure, -1, 0)]),
            new(7, SpaceType.Elite, 5, 5, 0, null),
            new(8, SpaceType.Random, 6, -1, 0, [new(SpaceType.Enemy, 6, 0), new(SpaceType.Treasure, -1, 0), new(SpaceType.Campsite, -1, 4)]),
            new(9, SpaceType.Treasure, 6, -1, 0, null),
            new(10, SpaceType.Elite, 7, 7, 0, null),
            new(11, SpaceType.Enemy, 7, 8, 0, null),
            new(12, SpaceType.Random, 8, -1, 0, [new(SpaceType.Enemy, 9, 0), new(SpaceType.Shop, -1, 0)]),
            new(13, SpaceType.Shop, 8, -1, 0, null),
            new(14, SpaceType.Boss, 9, 0, 0, null),
        ],
        [
            new(0, SpaceType.Start, 0, -1, 0, null),
            new(1, SpaceType.Enemy, 1, 1, 0, null),
            new(2, SpaceType.Elite, 2, 2, 0, null),
            new(3, SpaceType.Shop, 2, -1, 0, null),
            new(4, SpaceType.Campsite, 3, -1, 1, null),
            new(5, SpaceType.Treasure, 3, -1, 0, null),
            new(6, SpaceType.Random, 3, -1, 0, [new(SpaceType.Enemy, 3, 0), new(SpaceType.Treasure, -1, 0)]),
            new(7, SpaceType.Random, 4, -1, 0, [new(SpaceType.Enemy, 4, 0), new(SpaceType.Shop, -1, 0)]),
            new(8, SpaceType.Enemy, 4, 5, 0, null),
            new(9, SpaceType.Treasure, 4, -1, 0, null),
            new(10, SpaceType.Elite, 5, 6, 0, null),
            new(11, SpaceType.Campsite, 6, -1, 2, null),
            new(12, SpaceType.Random, 7, -1, 0, [new(SpaceType.Elite, 7, 0), new(SpaceType.Treasure, -1, 0)]),
            new(13, SpaceType.Shop, 7, -1, 0, null),
            new(14, SpaceType.Treasure, 8, -1, 0, null),
            new(15, SpaceType.Treasure, 8, -1, 0, null),
            new(16, SpaceType.Elite, 9, 8, 0, null),
            new(17, SpaceType.Enemy, 9, 9, 0, null),
            new(18, SpaceType.Enemy, 10, 10, 0, null),
            new(19, SpaceType.Shop, 11, -1, 0, null),
            new(20, SpaceType.Random, 12, -1, 0, [new(SpaceType.Enemy, 11, 0), new(SpaceType.Treasure, -1, 0)]),
            new(21, SpaceType.Campsite, 12, -1, 3, null),
            new(22, SpaceType.Treasure, 12, -1, 0, null),
            new(23, SpaceType.Random, 13, -1, 0, [new(SpaceType.Elite, 12, 0), new(SpaceType.Shop, -1, 0)]),
            new(24, SpaceType.Elite, 13, 13, 0, null),
            new(25, SpaceType.Boss, 14, 0, 0, null),
        ],
    ];

    /// <summary> Board graph edges (from space, to space), index = board (0 unused). </summary>
    public static readonly (int From, int To)[][] Edges =
    [
        [],
        [(0, 1), (1, 2), (1, 3), (2, 4), (3, 5), (4, 6), (5, 6), (6, 7), (7, 8), (8, 9), (8, 10), (9, 11), (10, 11), (11, 12)],
        [(0, 1), (1, 2), (2, 3), (2, 4), (3, 5), (4, 6), (5, 7), (6, 7), (7, 8), (8, 9), (9, 10), (9, 11), (10, 12), (11, 12), (12, 13)],
        [(0, 1), (1, 2), (2, 3), (3, 4), (3, 5), (4, 6), (5, 7), (6, 8), (7, 8), (8, 9), (8, 10), (9, 11), (10, 11), (11, 12), (12, 13), (12, 14), (13, 15), (14, 15), (15, 16)],
        [(0, 1), (1, 2), (1, 3), (2, 4), (3, 4), (4, 5), (4, 6), (5, 7), (6, 7), (7, 8), (7, 9), (8, 10), (9, 11), (10, 12), (11, 13), (12, 14), (13, 14)],
        [(0, 1), (1, 2), (1, 3), (2, 4), (2, 5), (3, 5), (3, 6), (4, 7), (5, 8), (6, 9), (7, 10), (8, 10), (9, 10), (10, 11), (11, 12), (11, 13), (12, 14), (13, 15), (14, 16), (15, 17), (16, 18), (17, 18), (18, 19), (19, 20), (19, 21), (19, 22), (20, 23), (21, 25), (22, 24), (23, 25), (24, 25)],
    ];
}
