<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>0.0.1.1</Version>
    <AssemblyName>LazyFATEAutomator</AssemblyName>
    <Description>Fully automated FATE grinding utilizing vnavmesh, lifestream, and Gluttony Combo IPC.</Description>
    <IsPackable>false</IsPackable>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <SupportedOSPlatformVersion>8.0</SupportedOSPlatformVersion>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Author>dajoey</Author>
    <Name>Lazy FATE Automator</Name>
    <InternalName>LazyFATEAutomator</InternalName>
    <Punchline>Fully automated FATE grinding utilizing vnavmesh, lifestream, and Gluttony Combo</Punchline>
    <ApplicableVersion>any</ApplicableVersion>
    <Tags>fate;automation;navigation;combat;vnavmesh</Tags>
    <CategoryTags>utility</CategoryTags>
    <DalamudApiLevel>15</DalamudApiLevel>
    <LoadRequiredState>0</LoadRequiredState>
    <LoadSync>false</LoadSync>
    <CanUnloadAsync>false</CanUnloadAsync>
    <LoadPriority>0</LoadPriority>
    <AcceptsFeedback>false</AcceptsFeedback>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="LazyFATEAutomator.json" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ECommons" Version="3.2.0.9" />
  </ItemGroup>
  <Target Name="PruneOutputDlls" AfterTargets="ResolveReferences">
    <ItemGroup>
      <_KeepDlls Include="@(ReferenceCopyLocalPaths)" Condition="           '%(Filename)' == 'LazyFATEAutomator' or           '%(Filename)' == 'ECommons'         " />
      <ReferenceCopyLocalPaths Remove="@(ReferenceCopyLocalPaths)" />
      <ReferenceCopyLocalPaths Include="@(_KeepDlls)" />
    </ItemGroup>
  </Target>
</Project>