// <auto-generated>
//   tools/crucible-planner/gen_guide_needs.py from src/LazyCrucible/Guide/CrucibleGuide.json. Do not edit by hand:
//   edit the guide, regenerate, and the LazyCrucible harness checks the table equals CrucibleGuide.NeedsOf.
// </auto-generated>
using System.Collections.Generic;

namespace Lalalazy.Crucible;

internal static partial class BST_CrucibleGuideNeeds
{
    /// <summary> Every fight guide counter that is an interrupt, dispel or cleanse, in guide order. </summary>
    private static readonly GuideNeedRow[] Rows =
    [
        new(1, 1, CrucibleNeeds.Interrupt, CrucibleNeedTier.Required, "Ossify (Knight, 8 s self buff)", ["panel"]),
        new(1, 1, CrucibleNeeds.Dispel, CrucibleNeedTier.Required, "Physical Damage Up from Ossify", ["panel"]),
        new(1, 1, CrucibleNeeds.Cleanse, CrucibleNeedTier.Required, "Windburn from Ancient Aero", ["panel"]),
        new(1, 3, CrucibleNeeds.Dispel, CrucibleNeedTier.Required, "Clear Mind (Damage Up on the Piscodemon)", ["panel"]),
        new(1, 4, CrucibleNeeds.Cleanse, CrucibleNeedTier.Required, "Poison from Deadly Thrust", ["panel"]),
        new(1, 0, CrucibleNeeds.Interrupt, CrucibleNeedTier.Required, "Fanaticism (Succubus Mage)", ["panel"]),
        new(1, 0, CrucibleNeeds.Dispel, CrucibleNeedTier.Required, "Damage Up on the boss from Fanaticism", ["panel"]),
        new(1, 0, CrucibleNeeds.Cleanse, CrucibleNeedTier.Required, "Poison from Cold Caress", ["panel"]),
        new(2, 5, CrucibleNeeds.Interrupt, CrucibleNeedTier.Required, "Rallying Cheer (Younger Tablitaur)", ["panel"]),
        new(2, 5, CrucibleNeeds.Dispel, CrucibleNeedTier.Required, "Damage Up on the Elder from Rallying Cheer", ["panel"]),
        new(2, 6, CrucibleNeeds.Cleanse, CrucibleNeedTier.Required, "Paralysis from Void Paralyze", ["panel"]),
        new(2, 0, CrucibleNeeds.Dispel, CrucibleNeedTier.Required, "Kinborrow (Popoto Skin on Loosefrox)", ["panel"]),
        new(2, 0, CrucibleNeeds.Cleanse, CrucibleNeedTier.Required, "Blind from Sand Breath", ["panel"]),
        new(3, 2, CrucibleNeeds.Interrupt, CrucibleNeedTier.Required, "Dreadwash (Sahagin Piece)", ["panel"]),
        new(3, 3, CrucibleNeeds.Interrupt, CrucibleNeedTier.Required, "Caustic Vomit (Pullet Piece)", ["panel"]),
        new(3, 5, CrucibleNeeds.Dispel, CrucibleNeedTier.Useful, "Might on the Golem (panel says not dispellable)", ["AS", "NT"]),
        new(4, 1, CrucibleNeeds.Dispel, CrucibleNeedTier.Required, "Ultimate Focus (Magic Damage Up)", ["panel"]),
        new(4, 2, CrucibleNeeds.Cleanse, CrucibleNeedTier.Required, "Paralysis from Extremely Bad Breath", ["panel"]),
        new(4, 2, CrucibleNeeds.Cleanse, CrucibleNeedTier.Required, "Poison from Seedling hits", ["panel"]),
        new(4, 2, CrucibleNeeds.Cleanse, CrucibleNeedTier.Required, "Paralysis from Carrion Broth hits", ["panel"]),
        new(4, 6, CrucibleNeeds.Interrupt, CrucibleNeedTier.Required, "Confound (Administrator)", ["panel"]),
        new(4, 6, CrucibleNeeds.Cleanse, CrucibleNeedTier.Required, "Poison from Noxious Nova", ["panel"]),
        new(4, 8, CrucibleNeeds.Interrupt, CrucibleNeedTier.Required, "Natural Nurture (Biloko Piece)", ["panel"]),
        new(4, 8, CrucibleNeeds.Dispel, CrucibleNeedTier.Useful, "Growing buff from Grab and Grow (panel says not dispellable)", ["AS"]),
        new(4, 9, CrucibleNeeds.Interrupt, CrucibleNeedTier.Required, "Massive Explosion (Progenitrix)", ["panel"]),
        new(4, 9, CrucibleNeeds.Dispel, CrucibleNeedTier.Required, "Ice Spikes (Snoll Piece)", ["panel"]),
        new(4, 9, CrucibleNeeds.Cleanse, CrucibleNeedTier.Required, "Poison from Toxic Fumes", ["panel"]),
        new(5, 1, CrucibleNeeds.Cleanse, CrucibleNeedTier.Required, "Paralysis from Erratic Blaster", ["panel"]),
        new(5, 2, CrucibleNeeds.Cleanse, CrucibleNeedTier.Required, "Paralysis from Void Paralyze III", ["panel"]),
        new(5, 2, CrucibleNeeds.Cleanse, CrucibleNeedTier.Required, "Poison from Myconid bursts", ["panel"]),
        new(5, 3, CrucibleNeeds.Cleanse, CrucibleNeedTier.Useful, "Blind from Ripples of Gloom", ["AS", "BMR"]),
        new(5, 5, CrucibleNeeds.Dispel, CrucibleNeedTier.Required, "Blaze Spikes (Drake Piece)", ["panel"]),
        new(5, 5, CrucibleNeeds.Dispel, CrucibleNeedTier.Required, "Regen on the Abaddon from eaten Morphos", ["AS", "LSB"]),
        new(5, 7, CrucibleNeeds.Interrupt, CrucibleNeedTier.Required, "Raise (Lamia Piece)", ["panel"]),
        new(5, 7, CrucibleNeeds.Cleanse, CrucibleNeedTier.Required, "Paralysis from Glower", ["panel"]),
        new(5, 7, CrucibleNeeds.Dispel, CrucibleNeedTier.Useful, "Impassion Damage Up (panel says not dispellable)", ["AS"]),
        new(5, 8, CrucibleNeeds.Cleanse, CrucibleNeedTier.Required, "Frostbite or Electrocution from the roars", ["panel"]),
        new(5, 8, CrucibleNeeds.Cleanse, CrucibleNeedTier.Required, "Poison from Toxic Tantrum", ["AS", "LSB", "BMR"]),
        new(5, 10, CrucibleNeeds.Interrupt, CrucibleNeedTier.Required, "Rupture (Congealed Lightning or Kindling)", ["panel"]),
        new(5, 10, CrucibleNeeds.Interrupt, CrucibleNeedTier.Required, "Camaraderie (Cyclops Piece)", ["panel"]),
        new(5, 10, CrucibleNeeds.Cleanse, CrucibleNeedTier.Required, "Paralysis from Glower", ["panel"]),
        new(5, 11, CrucibleNeeds.Dispel, CrucibleNeedTier.Required, "Spirit of Pompetition (Kinged Swordsmog)", ["panel"]),
        new(5, 12, CrucibleNeeds.Cleanse, CrucibleNeedTier.Required, "Paralysis from Cross Charge", ["panel"]),
        new(5, 13, CrucibleNeeds.Cleanse, CrucibleNeedTier.Required, "Burns from Straight Punch", ["panel"]),
        new(5, 0, CrucibleNeeds.Cleanse, CrucibleNeedTier.Useful, "Paralysis from Thunderbolt (panel says not cleansable)", ["AS", "LSB"]),
    ];
}
